Repository piretek/medical-center-cms, pull requests merged in 2020-05, with the labels that each got.

#13 Add dashboard pages
  assets/css/style.css
  create-patient-account.php
  includes/init.php
  index.php
  new-reservation.php
  reservations.php
  schedule.php
  user-account.php
  user-reservations.php
  users.php
  views/header.php
  views/navs/auth-nav.php
  views/navs/dashboard-nav.php
  views/navs/index-nav.php
Labels: enhancement

#14 Fix bad boot secure const
  create-patient-account.php
  includes/config.sample.php
  includes/init.php
  new-reservation.php
  reservations.php
  schedule.php
  user-account.php
  user-reservations.php
  users.php
  views/footer.php
  views/header.php
  views/navs/auth-nav.php
  views/navs/dashboard-nav.php
  views/navs/index-nav.php
Labels: bug

#15 Looped nav links & fix no secure boot in index.php
  index.php
  views/navs/auth-nav.php
  views/navs/index-nav.php
Labels: bug, enhancement

#17 Add permissions
  includes/database-schema.php
  includes/init.php
  views/navs/dashboard-nav.php
Labels: enhancement

#21 Logowanie i rejestracja
  auth.php
  includes/init.php
  login.php
  views/navs/auth-nav.php
Labels: enhancement

#22 Fix for Kowalsky last branch
  assets/css/style.css
  auth.php
  create-patient-account.php
  login.php
  views/navs/auth-nav.php
Labels: enhancement

#19 Zarządzanie dla pacjenta
  assets/css/style.css
  assets/img/done.svg
  assets/js/reservation.js
  auth.php
  create-patient-account.php
  includes/classes/form.php
  includes/classes/pesel-exception.php
  includes/classes/pesel.php
  includes/database-schema.php
  includes/functions/notification.php
  includes/functions/reservation-statuses-and-types.php
  includes/functions/verify-config.php
  includes/init.php
  login.php
  new-reservation.php
  user-account.php
  user-reservations.php
  views/forms/add-patient.php
  views/forms/doctor.php
  views/forms/edit-patient.php
Labels: enhancement

#29 Important fixes
  README.md
  database.sql
  user-reservations.php
Labels: documentation, enhancement

#26 Zarządzanie dla administratora
  README.md
  assets/css/style.css
  assets/js/main.js
  assets/js/reservation.js
  auth.php
  includes/classes/form.php
  includes/database-schema.php
  includes/database.php
  includes/functions/weekday.php
  includes/init.php
  new-reservation.php
  reservations.php
  schedule.php
  settings.php
  user-account.php
  user-reservations.php
  users.php
  views/forms/add-patient.php
  views/forms/edit-patient.php
  views/navs/dashboard-nav.php
Labels: enhancement

#20 Add about page
  about.php
  assets/css/style.css
  index.php
Labels: enhancement

#35 Responsive stylesheet
  about.php
  assets/css/style.css
  auth.php
  contact.php
  index.php
  user-reservations.php
  views/footer.php
Labels: enhancement

#36 Readme bump
  README.md
  login.php
Labels: enhancement
